### PR TITLE
Refactored Admin and Catalog

### PR DESCRIPTION
**Pull request by Codebytes**
Refactored Admin and Catalog
Added Tests
Renamed contexts to be similar
Updated to .NET 6

### CODE REVIEW

**Review by landonpierce — APPROVED** [review]
Looks good. See one quick comment I had.

**Comment by Codebytes** [comment]
We can reorganize.
Now or later?

**Comment by landonpierce** [comment]
We can do later. Go ahead and merge.

**Review by nickpinheiro — CHANGES_REQUESTED** [review]
Looking good.  Please be sure to also update the Provider web application App Service deployment (ARM) to target .NET 6 as well prior to merging.

**Comment by Codebytes** [comment]
I'm not going to make that change right now due to the blog and zip reference in the deployment but we will add a backlog item.

**Pull request merged**
