### PR TITLE
New readme

### PR DESCRIPTION
**Pull request by ytechie**
Streamlined the readme to make it friendly to new devs. It also gives us a nice jumping off point to grow into some of the other pieces we want to build/enhance.

### CODE REVIEW

**Review by arsenvlad — APPROVED** [review]
Looks great to me.

**Comment by ytechie** [comment]
Any more thoughts on this?

**Comment by nickpinheiro** [comment]
@ytechie Yes, I'm integrating this with a number of additional changes I'm making to the README.  Should all be in by Friday.

**Comment by nickpinheiro** [comment]
Thank you for submitting these recommendations @ytechie, @arsenvlad.  I've integrated these along with updates that came in through additional feedback and have published a new iteration of the README.

**Pull request closed without merging**
