### PR TITLE
Rename and refactor

### PR DESCRIPTION
**Pull request by Codebytes**
The big rename :)

### CODE REVIEW

**Comment by ytechie** [comment]
The structure looks good, but I'm getting an error on build:
image

**Comment by ytechie** [comment]
Works now. Thanks. Looks good to me, but will be good for someone else to review.

**Comment by Codebytes** [comment]
@ytechie  I checked in main, it wasn't building there either.
Those are the new auth lib and demo app.
I fixed the issues and they build now.  It wasn't caught before because pipelines weren't triggering them and I was working piecemeal.

**Review by landonpierce — APPROVED** [review]
Looks good to me. I did update the builds. We will need to rename the app services at some point but the existing ones suffice for now.

**Pull request merged**
